/*
 * This file is generated by jOOQ.
 */
package com.tigerpay.auth.model.jooq.schema;


import com.tigerpay.auth.model.jooq.schema.tables.Account;
import com.tigerpay.auth.model.jooq.schema.tables.AccountRole;
import com.tigerpay.auth.model.jooq.schema.tables.RefreshToken;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Represents user account as a general entity in our payment system
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * Represents role that account can have
     */
    public static final AccountRole ACCOUNT_ROLE = AccountRole.ACCOUNT_ROLE;

    /**
     * Stores refresh token data
     */
    public static final RefreshToken REFRESH_TOKEN = RefreshToken.REFRESH_TOKEN;
}
