/*
 * This file is generated by jOOQ.
 */
package com.tigerpay.payment.model.jooq.schema.tables.pojos;


import java.io.Serializable;


/**
 * Represents bank counterparty
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CounterpartyMetadataEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Integer ledger;

    public CounterpartyMetadataEntity() {}

    public CounterpartyMetadataEntity(CounterpartyMetadataEntity value) {
        this.id = value.id;
        this.ledger = value.ledger;
    }

    public CounterpartyMetadataEntity(
        Long id,
        Integer ledger
    ) {
        this.id = id;
        this.ledger = ledger;
    }

    /**
     * Getter for <code>public.counterparty_metadata.id</code>. Bank account ID
     * in TigerBeetle
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.counterparty_metadata.id</code>. Bank account ID
     * in TigerBeetle
     */
    public CounterpartyMetadataEntity setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.counterparty_metadata.ledger</code>. Bank ledger
     */
    public Integer getLedger() {
        return this.ledger;
    }

    /**
     * Setter for <code>public.counterparty_metadata.ledger</code>. Bank ledger
     */
    public CounterpartyMetadataEntity setLedger(Integer ledger) {
        this.ledger = ledger;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CounterpartyMetadataEntity other = (CounterpartyMetadataEntity) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ledger == null) {
            if (other.ledger != null)
                return false;
        }
        else if (!this.ledger.equals(other.ledger))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ledger == null) ? 0 : this.ledger.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CounterpartyMetadataEntity (");

        sb.append(id);
        sb.append(", ").append(ledger);

        sb.append(")");
        return sb.toString();
    }
}
