/*
 * This file is generated by jOOQ.
 */
package com.tigerpay.payment.model.jooq.schema;


import com.tigerpay.payment.model.jooq.schema.tables.PaymentAccount;

import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> PAYMENT_ACCOUNT_PK = Internal.createUniqueKey(PaymentAccount.PAYMENT_ACCOUNT, DSL.name("payment_account_pk"), new TableField[] { PaymentAccount.PAYMENT_ACCOUNT.ID }, true);
}
