/*
 * This file is generated by jOOQ.
 */
package com.tigerpay.payment.model.jooq.schema;


import com.tigerpay.payment.model.jooq.schema.tables.CounterpartyMetadata;
import com.tigerpay.payment.model.jooq.schema.tables.PaymentAccount;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Represents bank counterparty
     */
    public static final CounterpartyMetadata COUNTERPARTY_METADATA = CounterpartyMetadata.COUNTERPARTY_METADATA;

    /**
     * Represents the payment account
     */
    public static final PaymentAccount PAYMENT_ACCOUNT = PaymentAccount.PAYMENT_ACCOUNT;
}
