/*
 * This file is generated by jOOQ.
 */
package com.tigerpay.auth.model.jooq.schema.tables.pojos;


import java.io.Serializable;
import java.util.UUID;


/**
 * Represents role that account can have
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRoleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID uuid;
    private String key;
    private String label;

    public AccountRoleEntity() {}

    public AccountRoleEntity(AccountRoleEntity value) {
        this.uuid = value.uuid;
        this.key = value.key;
        this.label = value.label;
    }

    public AccountRoleEntity(
        UUID uuid,
        String key,
        String label
    ) {
        this.uuid = uuid;
        this.key = key;
        this.label = label;
    }

    /**
     * Getter for <code>public.account_role.uuid</code>. Role UUID
     */
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Setter for <code>public.account_role.uuid</code>. Role UUID
     */
    public AccountRoleEntity setUuid(UUID uuid) {
        this.uuid = uuid;
        return this;
    }

    /**
     * Getter for <code>public.account_role.key</code>. Role key, must be unique
     * and not null
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>public.account_role.key</code>. Role key, must be unique
     * and not null
     */
    public AccountRoleEntity setKey(String key) {
        this.key = key;
        return this;
    }

    /**
     * Getter for <code>public.account_role.label</code>. Role label, must not
     * be null
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Setter for <code>public.account_role.label</code>. Role label, must not
     * be null
     */
    public AccountRoleEntity setLabel(String label) {
        this.label = label;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AccountRoleEntity other = (AccountRoleEntity) obj;
        if (this.uuid == null) {
            if (other.uuid != null)
                return false;
        }
        else if (!this.uuid.equals(other.uuid))
            return false;
        if (this.key == null) {
            if (other.key != null)
                return false;
        }
        else if (!this.key.equals(other.key))
            return false;
        if (this.label == null) {
            if (other.label != null)
                return false;
        }
        else if (!this.label.equals(other.label))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.uuid == null) ? 0 : this.uuid.hashCode());
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.label == null) ? 0 : this.label.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountRoleEntity (");

        sb.append(uuid);
        sb.append(", ").append(key);
        sb.append(", ").append(label);

        sb.append(")");
        return sb.toString();
    }
}
