debug: true
server:
  port: 7000
db:
  url: jdbc:postgresql://localhost:5433/tigerpay_payment_db
  hikari:
    max-pool-size: 20
  username: tigerpay_dev
  password: tigerpay_dev
  driver:
    classname: org.postgresql.Driver
tigerbeetle:
  replica-addresses: 3000,3001,3002
  cluster-id: 0
jwt:
  secret: 7d29c3d95edabcbe07f4167962fefc60849497fcdae1a9d50540170b5cb3d9a0fe2efc6a5b1d1da4203265e87afa57003003e51f28ed0fb2730970385b1b54e1